### ISSUE TITLE
Old / dead API?

### ISSUE THREAD

**Issue by d4rkd0s** [workbooks/client_lib#8]
I've noticed this client_lib repo hasn't been updated in over a year and a half. That would be all good/fine except that concerns me Workbook hasn't added any features, since the client_lib's haven't been updated and there are a couple of issues filed, for instance #6 hasn't been answered since its creation over 6 months ago.

If someone could address my concerns and possibly make a CONTRIBUTING guide?

**Comment by d4rkd0s** [comment]
@workbooks also noticed a pull req from 2014... #5 that no one has addressed either. Which is sad. If someone wants to help improve your code, tell them whats wrong with it, or accept it in! It only helps everyone.

**Comment by workbooks** [comment]
Hello - Not old/dead.  What you are looking at is a set of wrappers for the API which you can find documented within Workbooks (Configuration > Automation > API Reference).  The wrappers are intended to be stable and change rarely, so should not need to be updated often.  We are proud that code written to our API 5 years ago will still work today.  

We have chosen not to pull issue #5 because it does not extend the scope of the API in a direction we need it to take. Issue #6 is an outstanding work item.

What are you looking to achieve with the API? Are there specific issues you have and which language are you looking to use?

**Comment by d4rkd0s** [comment]
As features are added to your server side, the client side libs arent updated? @workbooks

**Comment by d4rkd0s** [comment]
@workbooks Not sure why you closed this. Anyways, no need to provide us with libraries we would like to connect to workbooks over HTTP Representational state transfer. Is there docs for this?

https://spring.io/understanding/REST#http-methods

**Comment by workbooks** [comment]
These client side libraries are intended to make connection to WB easier. 

If you take a look at the documentation you'll see that the system is metadata-driven.  For example when we add a new object type (e.g. 'API Data') the client libraries do not need to change.  Customers can add their own custom fields which also extends the usable API, again there is no need to change the client libraries.  The client libraries are merely helpers for use when you are creating a request of interpreting the response from the service.

The Workbooks API is not strictly REST but is similar (it supports bulk changes for example).  If you don't want to use the bindings you see here on GitHub (which we recommend if you're using PHP, c#, Java or Ruby), the wire protocol is documented at https://www.workbooks.com/api-developer-guide

**Comment by workbooks** [comment]
Feel free to email us at support@workbooks.com if you would like more assistance.

**Comment by d4rkd0s** [comment]
@workbooks thank you!
